# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhPackageRetention < Formula
  desc "Package retention for github packages"
  homepage "https://github.com/DoodleScheduling/gh-package-retention"
  version "2.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.2/gh-package-retention_2.0.2_darwin_amd64.tar.gz"
      sha256 "f9d54064657421890515e3ef14a7cf6c6d9f10aa1aa845d68587a26ac0ae8fee"

      def install
        bin.install "gh-package-retention"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.2/gh-package-retention_2.0.2_darwin_arm64.tar.gz"
      sha256 "9faeb3f001c5f6cd574642f3e09841a72ba1528a98af85582c313054149a6c0c"

      def install
        bin.install "gh-package-retention"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.2/gh-package-retention_2.0.2_linux_arm64.tar.gz"
      sha256 "8281074d1a077c6d1f3492c94e2983f3bd324e72ba37478eba4a3e928f1cc53b"

      def install
        bin.install "gh-package-retention"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.2/gh-package-retention_2.0.2_linux_amd64.tar.gz"
      sha256 "70339cb31f46d593e14237b1ffb65829e4a6c091572a99fd088063f3aa5b15f0"

      def install
        bin.install "gh-package-retention"
      end
    end
  end

  test do
    system "#{bin}/gh-package-retention -h"
  end
end
