# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhPackageRetention < Formula
  desc "Package retention for github packages"
  homepage "https://github.com/DoodleScheduling/gh-package-retention"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.1/gh-package-retention_2.0.1_darwin_arm64.tar.gz"
      sha256 "6b805830358406a51940fbd7a8cae3b097c1739bc70f9c6c049800f085c49d82"

      def install
        bin.install "gh-package-retention"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.1/gh-package-retention_2.0.1_darwin_amd64.tar.gz"
      sha256 "1d688350bd68734e919146fcf1b617f420e1ce047f99f68bdd9069e5a2e9cb44"

      def install
        bin.install "gh-package-retention"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.1/gh-package-retention_2.0.1_linux_arm64.tar.gz"
      sha256 "6b097bbf6fa2b7bcbfb510c8450c47f8ff3cc2047495d7e6af84fa2ea672966d"

      def install
        bin.install "gh-package-retention"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/gh-package-retention/releases/download/v2.0.1/gh-package-retention_2.0.1_linux_amd64.tar.gz"
      sha256 "378f84e62bb3859a2093286dafe1aaded6b675b50fb3f3748f8392c635ac7622"

      def install
        bin.install "gh-package-retention"
      end
    end
  end

  test do
    system "#{bin}/gh-package-retention -h"
  end
end
